"""Overall (cross-position) 2026 standard-scoring ADP rankings, sourced from
fantasyfootballcalculator.com/adp/standard (fetched live, refreshed 2026-08-28).
Used to give the available-players page a single "who's the best player left"
ordering across all positions, distinct from each player's within-position rank
in pool.json. The site caps this list at its own ADP-relevant depth (222 rows as
of this fetch) -- players past that point have no meaningful ADP and are left
with overallRank=None by match_overall_ranks.py, which is expected, not a gap."""

# (overall_rank, name, team, pos) -- as fetched, name spellings as-is.
# pos "PK" from the source site is normalized to "K" here.
OVERALL_ADP = [
    (1, 'Jahmyr Gibbs', 'DET', 'RB'),
    (2, 'Bijan Robinson', 'ATL', 'RB'),
    (3, 'Puka Nacua', 'LAR', 'WR'),
    (4, 'Jonathan Taylor', 'IND', 'RB'),
    (5, "Ja'Marr Chase", 'CIN', 'WR'),
    (6, 'Jaxon Smith-Njigba', 'SEA', 'WR'),
    (7, 'Christian McCaffrey', 'SF', 'RB'),
    (8, 'Derrick Henry', 'BAL', 'RB'),
    (9, 'James Cook III', 'BUF', 'RB'),
    (10, 'Amon-Ra St. Brown', 'DET', 'WR'),
    (11, "De'Von Achane", 'MIA', 'RB'),
    (12, 'Saquon Barkley', 'PHI', 'RB'),
    (13, 'Drake London', 'ATL', 'WR'),
    (14, 'CeeDee Lamb', 'DAL', 'WR'),
    (15, 'Chase Brown', 'CIN', 'RB'),
    (16, 'Justin Jefferson', 'MIN', 'WR'),
    (17, 'Rashee Rice', 'KC', 'WR'),
    (18, 'George Pickens', 'DAL', 'WR'),
    (19, 'Nico Collins', 'HOU', 'WR'),
    (20, 'Josh Jacobs', 'GB', 'RB'),
    (21, 'Kenneth Walker', 'KC', 'RB'),
    (22, 'A.J. Brown', 'NE', 'WR'),
    (23, 'Ashton Jeanty', 'LV', 'RB'),
    (24, 'Kyren Williams', 'LAR', 'RB'),
    (25, 'Omarion Hampton', 'LAC', 'RB'),
    (26, 'Chris Olave', 'NO', 'WR'),
    (27, 'Zay Flowers', 'BAL', 'WR'),
    (28, 'Josh Allen', 'BUF', 'QB'),
    (29, 'Javonte Williams', 'DAL', 'RB'),
    (30, 'Malik Nabers', 'NYG', 'WR'),
    (31, 'Tetairoa McMillan', 'CAR', 'WR'),
    (32, 'Jeremiyah Love', 'ARI', 'RB'),
    (33, 'Breece Hall', 'NYJ', 'RB'),
    (34, 'Jameson Williams', 'DET', 'WR'),
    (35, 'Tee Higgins', 'CIN', 'WR'),
    (36, 'Emeka Egbuka', 'TB', 'WR'),
    (37, 'Davante Adams', 'LAR', 'WR'),
    (38, 'Cam Skattebo', 'NYG', 'RB'),
    (39, 'DeVonta Smith', 'PHI', 'WR'),
    (40, 'Travis Etienne Jr.', 'NO', 'RB'),
    (41, 'Garrett Wilson', 'NYJ', 'WR'),
    (42, "D'Andre Swift", 'CHI', 'RB'),
    (43, 'Ladd McConkey', 'LAC', 'WR'),
    (44, 'Terry McLaurin', 'WAS', 'WR'),
    (45, 'Rome Odunze', 'CHI', 'WR'),
    (46, 'Bucky Irving', 'TB', 'RB'),
    (47, 'Bhayshul Tuten', 'JAX', 'RB'),
    (48, 'DJ Moore', 'BUF', 'WR'),
    (49, 'Drake Maye', 'NE', 'QB'),
    (50, 'Quinshon Judkins', 'CLE', 'RB'),
    (51, 'Christian Watson', 'GB', 'WR'),
    (52, 'Trey McBride', 'ARI', 'TE'),
    (53, 'Brock Bowers', 'LV', 'TE'),
    (54, 'David Montgomery', 'HOU', 'RB'),
    (55, 'Mike Evans', 'SF', 'WR'),
    (56, 'Jaylen Waddle', 'DEN', 'WR'),
    (57, 'Alec Pierce', 'IND', 'WR'),
    (58, 'Lamar Jackson', 'BAL', 'QB'),
    (59, 'Joe Burrow', 'CIN', 'QB'),
    (60, 'TreVeyon Henderson', 'NE', 'RB'),
    (61, 'Luther Burden III', 'CHI', 'WR'),
    (62, 'Courtland Sutton', 'DEN', 'WR'),
    (63, 'Rhamondre Stevenson', 'NE', 'RB'),
    (64, 'DK Metcalf', 'PIT', 'WR'),
    (65, 'Tony Pollard', 'TEN', 'RB'),
    (66, 'Parker Washington', 'JAX', 'WR'),
    (67, 'Jaylen Warren', 'PIT', 'RB'),
    (68, 'Marvin Harrison Jr.', 'ARI', 'WR'),
    (69, 'Dak Prescott', 'DAL', 'QB'),
    (70, 'Colston Loveland', 'CHI', 'TE'),
    (71, 'Jadarian Price', 'SEA', 'RB'),
    (72, 'Jayden Daniels', 'WAS', 'QB'),
    (73, 'Brian Thomas Jr.', 'JAX', 'WR'),
    (74, 'Matthew Stafford', 'LAR', 'QB'),
    (75, 'Carnell Tate', 'TEN', 'WR'),
    (76, 'J.K. Dobbins', 'DEN', 'RB'),
    (77, 'Rico Dowdle', 'PIT', 'RB'),
    (78, 'Michael Wilson', 'ARI', 'WR'),
    (79, 'Quentin Johnston', 'LAC', 'WR'),
    (80, 'Tyler Warren', 'IND', 'TE'),
    (81, 'Chris Godwin Jr.', 'TB', 'WR'),
    (82, 'Jalen Hurts', 'PHI', 'QB'),
    (83, 'Jordan Addison', 'MIN', 'WR'),
    (84, 'Chuba Hubbard', 'CAR', 'RB'),
    (85, 'Seattle Defense', 'SEA', 'DEF'),
    (86, 'Tucker Kraft', 'GB', 'TE'),
    (87, 'Jakobi Meyers', 'JAX', 'WR'),
    (88, 'Jayden Reed', 'GB', 'WR'),
    (89, 'Jacory Croskey-Merritt', 'WAS', 'RB'),
    (90, 'Trevor Lawrence', 'JAX', 'QB'),
    (91, 'Brock Purdy', 'SF', 'QB'),
    (92, 'Jonathon Brooks', 'CAR', 'RB'),
    (93, 'Caleb Williams', 'CHI', 'QB'),
    (94, 'Xavier Worthy', 'KC', 'WR'),
    (95, 'Denver Defense', 'DEN', 'DEF'),
    (96, 'Michael Pittman Jr.', 'PIT', 'WR'),
    (97, 'Deebo Samuel Sr.', 'SF', 'WR'),
    (98, 'Matthew Golden', 'GB', 'WR'),
    (99, 'Kyle Monangai', 'CHI', 'RB'),
    (100, 'Dallas Goedert', 'PHI', 'TE'),
    (101, 'Jordan Mason', 'MIN', 'RB'),
    (102, 'Stefon Diggs', 'WAS', 'WR'),
    (103, 'Harold Fannin Jr.', 'CLE', 'TE'),
    (104, 'Josh Downs', 'IND', 'WR'),
    (105, 'Houston Defense', 'HOU', 'DEF'),
    (106, 'Romeo Doubs', 'NE', 'WR'),
    (107, 'Jared Goff', 'DET', 'QB'),
    (108, "Wan'Dale Robinson", 'TEN', 'WR'),
    (109, 'Blake Corum', 'LAR', 'RB'),
    (110, 'Patrick Mahomes', 'KC', 'QB'),
    (111, 'Makai Lemon', 'PHI', 'WR'),
    (112, 'Kyle Pitts Sr.', 'ATL', 'TE'),
    (113, 'Rashid Shaheed', 'SEA', 'WR'),
    (114, 'Justin Herbert', 'LAC', 'QB'),
    (115, 'LA Rams Defense', 'LAR', 'DEF'),
    (116, 'RJ Harvey', 'DEN', 'RB'),
    (117, 'Khalil Shakir', 'BUF', 'WR'),
    (118, 'KC Concepcion', 'CLE', 'WR'),
    (119, 'Aaron Jones Sr.', 'MIN', 'RB'),
    (120, 'George Kittle', 'SF', 'TE'),
    (121, 'Minnesota Defense', 'MIN', 'DEF'),
    (122, 'Jalen Coker', 'CAR', 'WR'),
    (123, 'Bo Nix', 'DEN', 'QB'),
    (124, 'Mark Andrews', 'BAL', 'TE'),
    (125, 'Jaxson Dart', 'NYG', 'QB'),
    (126, 'Kenny Gainwell', 'TB', 'RB'),
    (127, 'Detroit Defense', 'DET', 'DEF'),
    (128, 'Sam LaPorta', 'DET', 'TE'),
    (129, "De'Zhaun Stribling", 'SF', 'WR'),
    (130, 'Jerry Jeudy', 'CLE', 'WR'),
    (131, 'Brandon Aubrey', 'DAL', 'K'),
    (132, 'Tre Tucker', 'LV', 'WR'),
    (133, 'Jason Myers', 'SEA', 'K'),
    (134, 'Rachaad White', 'WAS', 'RB'),
    (135, 'Zach Charbonnet', 'SEA', 'RB'),
    (136, 'Jalen McMillan', 'TB', 'WR'),
    (137, 'New England Defense', 'NE', 'DEF'),
    (138, 'Rashod Bateman', 'BAL', 'WR'),
    (139, "Ka'imi Fairbairn", 'HOU', 'K'),
    (140, 'Calvin Ridley', 'TEN', 'WR'),
    (141, 'Philadelphia Defense', 'PHI', 'DEF'),
    (142, 'Baker Mayfield', 'TB', 'QB'),
    (143, 'Woody Marks', 'HOU', 'RB'),
    (144, 'Denzel Boston', 'CLE', 'WR'),
    (145, 'Pittsburgh Defense', 'PIT', 'DEF'),
    (146, 'Travis Kelce', 'KC', 'TE'),
    (147, 'Jauan Jennings', 'MIN', 'WR'),
    (148, 'Jalen Nailor', 'LV', 'WR'),
    (149, 'Isaiah Likely', 'NYG', 'TE'),
    (150, 'Keenan Allen', 'IND', 'WR'),
    (151, 'Harrison Mevis', 'LAR', 'K'),
    (152, 'Cameron Dicker', 'LAC', 'K'),
    (153, 'Braelon Allen', 'NYJ', 'RB'),
    (154, 'Tyler Shough', 'NO', 'QB'),
    (155, 'Dalton Kincaid', 'BUF', 'TE'),
    (156, 'LA Chargers Defense', 'LAC', 'DEF'),
    (157, 'Kyler Murray', 'MIN', 'QB'),
    (158, 'Tyler Loop', 'BAL', 'K'),
    (159, 'Chris Rodriguez Jr.', 'JAX', 'RB'),
    (160, 'Chase McLaughlin', 'TB', 'K'),
    (161, 'Jake Bates', 'DET', 'K'),
    (162, 'Cam Little', 'JAX', 'K'),
    (163, 'Mike Washington Jr.', 'LV', 'RB'),
    (164, 'Isaac TeSlaa', 'DET', 'WR'),
    (165, 'Tank Dell', 'HOU', 'WR'),
    (166, 'Malik Washington', 'MIA', 'WR'),
    (167, 'Sam Darnold', 'SEA', 'QB'),
    (168, 'Hunter Henry', 'NE', 'TE'),
    (169, "Ja'Kobi Lane", 'BAL', 'WR'),
    (170, 'Dontayvion Wicks', 'PHI', 'WR'),
    (171, 'Jake Ferguson', 'DAL', 'TE'),
    (172, 'Tyler Allgeier', 'ARI', 'RB'),
    (173, 'Alvin Kamara', 'NO', 'RB'),
    (174, 'Tank Bigsby', 'PHI', 'RB'),
    (175, 'Jordan Love', 'GB', 'QB'),
    (176, 'Keaton Mitchell', 'LAC', 'RB'),
    (177, 'Kaelon Black', 'SF', 'RB'),
    (178, 'MarShawn Lloyd', 'GB', 'RB'),
    (179, 'Cooper Kupp', 'SEA', 'WR'),
    (180, 'Dallas Defense', 'DAL', 'DEF'),
    (181, 'Cyrus Allen', 'KC', 'WR'),
    (182, 'Isiah Pacheco', 'DET', 'RB'),
    (183, 'Jordyn Tyson', 'NO', 'WR'),
    (184, 'Tyjae Spears', 'TEN', 'RB'),
    (185, 'Jonah Coleman', 'DEN', 'RB'),
    (186, 'Chris Boswell', 'PIT', 'K'),
    (187, 'Jacksonville Defense', 'JAX', 'DEF'),
    (188, 'Kayshon Boutte', 'HOU', 'WR'),
    (189, 'Kimani Vidal', 'LAC', 'RB'),
    (190, 'Trey Smack', 'GB', 'K'),
    (191, 'Juwan Johnson', 'NO', 'TE'),
    (192, 'Caleb Douglas', 'MIA', 'WR'),
    (193, 'Eddy Piñeiro', 'SF', 'K'),
    (194, 'Cleveland Defense', 'CLE', 'DEF'),
    (195, 'Will Reichard', 'MIN', 'K'),
    (196, 'Ray Davis', 'BUF', 'RB'),
    (197, 'Malik Willis', 'MIA', 'QB'),
    (198, 'Fernando Mendoza', 'LV', 'QB'),
    (199, 'Baltimore Defense', 'BAL', 'DEF'),
    (200, 'Bub Means', 'NO', 'WR'),
    (201, 'New Orleans Defense', 'NO', 'DEF'),
    (202, 'Adonai Mitchell', 'NYJ', 'WR'),
    (203, 'Buffalo Defense', 'BUF', 'DEF'),
    (204, 'Harrison Butker', 'KC', 'K'),
    (205, 'Atlanta Defense', 'ATL', 'DEF'),
    (206, 'Brenton Strange', 'JAX', 'TE'),
    (207, 'Tyler Bass', 'BUF', 'K'),
    (208, 'Ryan Flournoy', 'DAL', 'WR'),
    (209, 'Wil Lutz', 'DEN', 'K'),
    (210, "Tre' Harris", 'LAC', 'WR'),
    (211, 'Cairo Santos', 'CHI', 'K'),
    (212, 'Tennessee Defense', 'TEN', 'DEF'),
    (213, 'C.J. Stroud', 'HOU', 'QB'),
    (214, 'Travis Hunter', 'JAX', 'WR'),
    (215, 'Darius Slayton', 'NYG', 'WR'),
    (216, 'Tyrone Tracy Jr.', 'NYG', 'RB'),
    (217, 'Blake Grupe', 'IND', 'K'),
    (218, 'Evan McPherson', 'CIN', 'K'),
    (219, 'Devaughn Vele', 'NO', 'WR'),
    (220, 'Brian Robinson', 'ATL', 'RB'),
    (221, 'Daniel Jones', 'IND', 'QB'),
    (222, 'Andy Borregales', 'NE', 'K'),
]
