"""Overall (cross-position) 2026 standard-scoring ADP rankings, sourced from
fantasyfootballcalculator.com/adp/standard (fetched live, refreshed 2026-08-24).
Used to give the available-players page a single "who's the best player left"
ordering across all positions, distinct from each player's within-position rank
in pool.json. The site caps this list at its own ADP-relevant depth (217 rows as
of this fetch) -- players past that point have no meaningful ADP and are left
with overallRank=None by match_overall_ranks.py, which is expected, not a gap."""

# (overall_rank, name, team, pos) -- as fetched, name spellings as-is.
# pos "PK" from the source site is normalized to "K" here.
OVERALL_ADP = [
    (1, 'Jahmyr Gibbs', 'DET', 'RB'),
    (2, 'Bijan Robinson', 'ATL', 'RB'),
    (3, 'Puka Nacua', 'LAR', 'WR'),
    (4, 'Jonathan Taylor', 'IND', 'RB'),
    (5, "Ja'Marr Chase", 'CIN', 'WR'),
    (6, 'Jaxon Smith-Njigba', 'SEA', 'WR'),
    (7, 'Christian McCaffrey', 'SF', 'RB'),
    (8, 'Derrick Henry', 'BAL', 'RB'),
    (9, 'Amon-Ra St. Brown', 'DET', 'WR'),
    (10, 'James Cook III', 'BUF', 'RB'),
    (11, "De'Von Achane", 'MIA', 'RB'),
    (12, 'Drake London', 'ATL', 'WR'),
    (13, 'Saquon Barkley', 'PHI', 'RB'),
    (14, 'CeeDee Lamb', 'DAL', 'WR'),
    (15, 'Ashton Jeanty', 'LV', 'RB'),
    (16, 'Justin Jefferson', 'MIN', 'WR'),
    (17, 'Chase Brown', 'CIN', 'RB'),
    (18, 'Rashee Rice', 'KC', 'WR'),
    (19, 'George Pickens', 'DAL', 'WR'),
    (20, 'Nico Collins', 'HOU', 'WR'),
    (21, 'Kenneth Walker', 'KC', 'RB'),
    (22, 'Josh Jacobs', 'GB', 'RB'),
    (23, 'A.J. Brown', 'NE', 'WR'),
    (24, 'Kyren Williams', 'LAR', 'RB'),
    (25, 'Omarion Hampton', 'LAC', 'RB'),
    (26, 'Zay Flowers', 'BAL', 'WR'),
    (27, 'Chris Olave', 'NO', 'WR'),
    (28, 'Josh Allen', 'BUF', 'QB'),
    (29, 'Javonte Williams', 'DAL', 'RB'),
    (30, 'Malik Nabers', 'NYG', 'WR'),
    (31, 'Jeremiyah Love', 'ARI', 'RB'),
    (32, 'Jameson Williams', 'DET', 'WR'),
    (33, 'Tetairoa McMillan', 'CAR', 'WR'),
    (34, 'Emeka Egbuka', 'TB', 'WR'),
    (35, 'Breece Hall', 'NYJ', 'RB'),
    (36, 'Tee Higgins', 'CIN', 'WR'),
    (37, 'Davante Adams', 'LAR', 'WR'),
    (38, 'Cam Skattebo', 'NYG', 'RB'),
    (39, 'DeVonta Smith', 'PHI', 'WR'),
    (40, 'Travis Etienne Jr.', 'NO', 'RB'),
    (41, 'Garrett Wilson', 'NYJ', 'WR'),
    (42, "D'Andre Swift", 'CHI', 'RB'),
    (43, 'Terry McLaurin', 'WAS', 'WR'),
    (44, 'Ladd McConkey', 'LAC', 'WR'),
    (45, 'Rome Odunze', 'CHI', 'WR'),
    (46, 'Bucky Irving', 'TB', 'RB'),
    (47, 'Bhayshul Tuten', 'JAX', 'RB'),
    (48, 'Brock Bowers', 'LV', 'TE'),
    (49, 'Trey McBride', 'ARI', 'TE'),
    (50, 'Drake Maye', 'NE', 'QB'),
    (51, 'Quinshon Judkins', 'CLE', 'RB'),
    (52, 'DJ Moore', 'BUF', 'WR'),
    (53, 'Christian Watson', 'GB', 'WR'),
    (54, 'David Montgomery', 'HOU', 'RB'),
    (55, 'Mike Evans', 'SF', 'WR'),
    (56, 'Alec Pierce', 'IND', 'WR'),
    (57, 'Jaylen Waddle', 'DEN', 'WR'),
    (58, 'Lamar Jackson', 'BAL', 'QB'),
    (59, 'Joe Burrow', 'CIN', 'QB'),
    (60, 'TreVeyon Henderson', 'NE', 'RB'),
    (61, 'Courtland Sutton', 'DEN', 'WR'),
    (62, 'Tony Pollard', 'TEN', 'RB'),
    (63, 'Luther Burden III', 'CHI', 'WR'),
    (64, 'DK Metcalf', 'PIT', 'WR'),
    (65, 'Parker Washington', 'JAX', 'WR'),
    (66, 'Marvin Harrison Jr.', 'ARI', 'WR'),
    (67, 'Jaylen Warren', 'PIT', 'RB'),
    (68, 'Rhamondre Stevenson', 'NE', 'RB'),
    (69, 'Dak Prescott', 'DAL', 'QB'),
    (70, 'Colston Loveland', 'CHI', 'TE'),
    (71, 'Brian Thomas Jr.', 'JAX', 'WR'),
    (72, 'Jadarian Price', 'SEA', 'RB'),
    (73, 'Carnell Tate', 'TEN', 'WR'),
    (74, 'Jayden Daniels', 'WAS', 'QB'),
    (75, 'J.K. Dobbins', 'DEN', 'RB'),
    (76, 'Rico Dowdle', 'PIT', 'RB'),
    (77, 'Matthew Stafford', 'LAR', 'QB'),
    (78, 'Michael Wilson', 'ARI', 'WR'),
    (79, 'Quentin Johnston', 'LAC', 'WR'),
    (80, 'Chris Godwin Jr.', 'TB', 'WR'),
    (81, 'Tyler Warren', 'IND', 'TE'),
    (82, 'Jalen Hurts', 'PHI', 'QB'),
    (83, 'Chuba Hubbard', 'CAR', 'RB'),
    (84, 'Jordan Addison', 'MIN', 'WR'),
    (85, 'Seattle Defense', 'SEA', 'DEF'),
    (86, 'Jakobi Meyers', 'JAX', 'WR'),
    (87, 'Tucker Kraft', 'GB', 'TE'),
    (88, 'Jayden Reed', 'GB', 'WR'),
    (89, 'Jacory Croskey-Merritt', 'WAS', 'RB'),
    (90, 'Xavier Worthy', 'KC', 'WR'),
    (91, 'Michael Pittman Jr.', 'PIT', 'WR'),
    (92, 'Brock Purdy', 'SF', 'QB'),
    (93, 'Caleb Williams', 'CHI', 'QB'),
    (94, 'Denver Defense', 'DEN', 'DEF'),
    (95, 'Trevor Lawrence', 'JAX', 'QB'),
    (96, 'Matthew Golden', 'GB', 'WR'),
    (97, 'Kyle Monangai', 'CHI', 'RB'),
    (98, 'Josh Downs', 'IND', 'WR'),
    (99, 'Dallas Goedert', 'PHI', 'TE'),
    (100, 'Harold Fannin Jr.', 'CLE', 'TE'),
    (101, 'Deebo Samuel Sr.', 'SF', 'WR'),
    (102, 'Stefon Diggs', 'WAS', 'WR'),
    (103, 'Jonathon Brooks', 'CAR', 'RB'),
    (104, 'Houston Defense', 'HOU', 'DEF'),
    (105, 'Romeo Doubs', 'NE', 'WR'),
    (106, "Wan'Dale Robinson", 'TEN', 'WR'),
    (107, 'Jordan Mason', 'MIN', 'RB'),
    (108, 'Jared Goff', 'DET', 'QB'),
    (109, 'Makai Lemon', 'PHI', 'WR'),
    (110, 'RJ Harvey', 'DEN', 'RB'),
    (111, 'Kyle Pitts Sr.', 'ATL', 'TE'),
    (112, 'Patrick Mahomes', 'KC', 'QB'),
    (113, 'Blake Corum', 'LAR', 'RB'),
    (114, 'Rashid Shaheed', 'SEA', 'WR'),
    (115, 'Aaron Jones Sr.', 'MIN', 'RB'),
    (116, 'Justin Herbert', 'LAC', 'QB'),
    (117, 'LA Rams Defense', 'LAR', 'DEF'),
    (118, 'Minnesota Defense', 'MIN', 'DEF'),
    (119, 'Khalil Shakir', 'BUF', 'WR'),
    (120, 'Sam LaPorta', 'DET', 'TE'),
    (121, 'KC Concepcion', 'CLE', 'WR'),
    (122, 'Jayden Higgins', 'HOU', 'WR'),
    (123, 'Bo Nix', 'DEN', 'QB'),
    (124, 'Jalen Coker', 'CAR', 'WR'),
    (125, 'Jaxson Dart', 'NYG', 'QB'),
    (126, 'George Kittle', 'SF', 'TE'),
    (127, 'Kenny Gainwell', 'TB', 'RB'),
    (128, 'Detroit Defense', 'DET', 'DEF'),
    (129, 'Rachaad White', 'WAS', 'RB'),
    (130, 'Jerry Jeudy', 'CLE', 'WR'),
    (131, 'Tre Tucker', 'LV', 'WR'),
    (132, 'Brandon Aubrey', 'DAL', 'K'),
    (133, 'Jalen McMillan', 'TB', 'WR'),
    (134, "De'Zhaun Stribling", 'SF', 'WR'),
    (135, 'Zach Charbonnet', 'SEA', 'RB'),
    (136, 'Mark Andrews', 'BAL', 'TE'),
    (137, "Ka'imi Fairbairn", 'HOU', 'K'),
    (138, 'New England Defense', 'NE', 'DEF'),
    (139, 'Rashod Bateman', 'BAL', 'WR'),
    (140, 'Jason Myers', 'SEA', 'K'),
    (141, 'Calvin Ridley', 'TEN', 'WR'),
    (142, 'Pittsburgh Defense', 'PIT', 'DEF'),
    (143, 'Baker Mayfield', 'TB', 'QB'),
    (144, 'Jalen Nailor', 'LV', 'WR'),
    (145, 'Braelon Allen', 'NYJ', 'RB'),
    (146, 'Jordyn Tyson', 'NO', 'WR'),
    (147, 'Travis Kelce', 'KC', 'TE'),
    (148, 'Woody Marks', 'HOU', 'RB'),
    (149, 'Keenan Allen', 'IND', 'WR'),
    (150, 'Tyler Shough', 'NO', 'QB'),
    (151, 'Philadelphia Defense', 'PHI', 'DEF'),
    (152, 'Isaiah Likely', 'NYG', 'TE'),
    (153, 'Jauan Jennings', 'MIN', 'WR'),
    (154, 'Denzel Boston', 'CLE', 'WR'),
    (155, 'Cameron Dicker', 'LAC', 'K'),
    (156, 'Kaelon Black', 'SF', 'RB'),
    (157, 'Chase McLaughlin', 'TB', 'K'),
    (158, 'Harrison Mevis', 'LAR', 'K'),
    (159, 'Jake Bates', 'DET', 'K'),
    (160, 'Jonah Coleman', 'DEN', 'RB'),
    (161, 'Cam Little', 'JAX', 'K'),
    (162, 'Chris Rodriguez Jr.', 'JAX', 'RB'),
    (163, 'Hunter Henry', 'NE', 'TE'),
    (164, 'Kyler Murray', 'MIN', 'QB'),
    (165, 'Jake Ferguson', 'DAL', 'TE'),
    (166, 'Dalton Kincaid', 'BUF', 'TE'),
    (167, 'LA Chargers Defense', 'LAC', 'DEF'),
    (168, 'MarShawn Lloyd', 'GB', 'RB'),
    (169, 'Alvin Kamara', 'NO', 'RB'),
    (170, 'Tyler Loop', 'BAL', 'K'),
    (171, "Ja'Kobi Lane", 'BAL', 'WR'),
    (172, 'Cooper Kupp', 'SEA', 'WR'),
    (173, 'Tyjae Spears', 'TEN', 'RB'),
    (174, 'Tank Dell', 'HOU', 'WR'),
    (175, 'Dallas Defense', 'DAL', 'DEF'),
    (176, 'Sam Darnold', 'SEA', 'QB'),
    (177, 'Tyrone Tracy Jr.', 'NYG', 'RB'),
    (178, 'Tank Bigsby', 'PHI', 'RB'),
    (179, 'Keaton Mitchell', 'LAC', 'RB'),
    (180, 'Jordan Love', 'GB', 'QB'),
    (181, 'Isaac TeSlaa', 'DET', 'WR'),
    (182, 'Malik Washington', 'MIA', 'WR'),
    (183, 'Kayshon Boutte', 'NE', 'WR'),
    (184, 'Tyler Allgeier', 'ARI', 'RB'),
    (185, 'Isiah Pacheco', 'DET', 'RB'),
    (186, 'Mike Washington Jr.', 'LV', 'RB'),
    (187, 'Dontayvion Wicks', 'PHI', 'WR'),
    (188, 'Jacksonville Defense', 'JAX', 'DEF'),
    (189, 'New Orleans Defense', 'NO', 'DEF'),
    (190, 'Brenton Strange', 'JAX', 'TE'),
    (191, 'Cleveland Defense', 'CLE', 'DEF'),
    (192, 'Ray Davis', 'BUF', 'RB'),
    (193, 'Chris Boswell', 'PIT', 'K'),
    (194, 'Kimani Vidal', 'LAC', 'RB'),
    (195, 'Malik Willis', 'MIA', 'QB'),
    (196, 'Baltimore Defense', 'BAL', 'DEF'),
    (197, 'Cairo Santos', 'CHI', 'K'),
    (198, 'Will Reichard', 'MIN', 'K'),
    (199, 'Ryan Flournoy', 'DAL', 'WR'),
    (200, 'Buffalo Defense', 'BUF', 'DEF'),
    (201, 'Eddy Piñeiro', 'SF', 'K'),
    (202, 'Trey Smack', 'GB', 'K'),
    (203, 'Adonai Mitchell', 'NYJ', 'WR'),
    (204, 'Wil Lutz', 'DEN', 'K'),
    (205, 'Evan McPherson', 'CIN', 'K'),
    (206, 'Tennessee Defense', 'TEN', 'DEF'),
    (207, 'Brian Robinson', 'ATL', 'RB'),
    (208, 'Travis Hunter', 'JAX', 'WR'),
    (209, 'Blake Grupe', 'IND', 'K'),
    (210, 'Antonio Williams', 'WAS', 'WR'),
    (211, 'Green Bay Defense', 'GB', 'DEF'),
    (212, 'Harrison Butker', 'KC', 'K'),
    (213, 'Devaughn Vele', 'NO', 'WR'),
    (214, 'C.J. Stroud', 'HOU', 'QB'),
    (215, 'Fernando Mendoza', 'LV', 'QB'),
    (216, 'Omar Cooper Jr.', 'NYJ', 'WR'),
    (217, 'Andy Borregales', 'NE', 'K'),
]
